version: 0.2

phases:
  install:
    runtime-versions:
      gcc: 7   # Especifica la versión de GCC que deseas utilizar
    commands:
      - apt update
      - apt install -y git g++ libboost-all-dev libssl-dev libcpprest-dev libgtest-dev
  pre_build:
    commands:
      - cd cppProductsRestApi/src
      - g++ -std=c++11 -o productsapp main.cpp functions.cpp -lcpprest -lboost_system -lssl -lcrypto
      - g++ -std=c++11 -o runUnitTest unitTest.cpp functions.cpp -lgtest -lgtest_main -lpthread -lcpprest -lboost_system -lssl -lcrypto
  build:
    commands:
      - ./runUnitTest
  post_build:
    commands:
      - ./productsapp &
