version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - cd cppProductsRestApi
      - docker build -t $IMAGE_NAME .
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $IMAGE_NAME