version: 0.2

phases:
  pre_build:
    commands:
      # Configura Docker
      - echo Logging in to Docker Hub...
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      
  build:
    commands:
      # Construye la imagen de Docker
      - docker build -t sarodriel/cppproducts:latest .
      
  post_build:
    commands:
      # Etiqueta la imagen
      - docker tag sarodriel/cppproducts:latest sarodriel/cppproducts:latest
      # Sube la imagen a Docker Hub
      - docker push sarodriel/cppproducts:latest
