name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 3  # Establece el límite de tiempo en 10 minutos


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git g++ libboost-all-dev libssl-dev libcpprest-dev libgtest-dev
        dpkg -l | grep libcpprest

    - name: Clone project
      run: git clone https://github.com/jhonarias91/cppProductsRestApi.git

    - name: Set permissions
      run: sudo chmod -R 777 cppProductsRestApi

    - name: Compile program
      run: |
        cd cppProductsRestApi/src
        g++ -std=c++11 -o productsapp  main.cpp functions.cpp -lcpprest -lboost_system -lssl -lcrypto


    - name: Compile unit tests
      run: |
        cd cppProductsRestApi/src
        g++ -std=c++11 -o runUnitTest unitTest.cpp functions.cpp -lgtest -lgtest_main -lpthread -lcpprest -lboost_system -lssl -lcrypto

    - name: Run program and unit tests
      run: |
          ./cppProductsRestApi/src/productsapp &&
          ./cppProductsRestApi/src/runUnitTest
      


